language: python

python:
- 3.7

dist: xenial

sudo: true

addons:
  apt_packages:
  - libcups2-dev
  hostname: ambition
services:
- mysql
branches:
  only:
  - develop
install:
- pip install --upgrade pip
- pip install -e .
- pip install -r requirements.txt
- pip install flake8 coveralls
before_script:
- flake8 ambition-screening
- mysql -e 'create database edc character set utf8;'
script:
- coverage run --source=ambition_screening manage.py test
after_success:
- coveralls
